#!/usr/bin/env bash

#  Copyright (C) 2019-2020 Maker Ecosystem Growth Holdings, INC.

#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

# shellcheck source=lib/common.sh
. "$LIB_DIR/common.sh"

if [[ -z "$BUSDDAI" ]]; then
    BUSDDAI=$(dappCreate binance-fl-ct-optimized PancakePairUSDTUSDCStub "$(seth --to-uint256 "$(seth --to-wei 1000000 ETH)")")
    log "BUSDDAI=$BUSDDAI"
    export BUSDDAI
fi

token=BUSDDAI
type=$(jq -r ".tokens.${token} | .pipDeploy | .type | values" "$CONFIG_FILE")
if [[ "${type}" == "freeliquid" ]]; then

	{ test "$BUSDDAI" == ""; } && echo "No parameters for BUSDDAI oracle" && exit 1
	sethSend "$VAL_BUSDDAI" "setup(address)" "$BUSDDAI"
fi

# shellcheck source=libexec/dss/deploy-ilk
. "$LIBEXEC_DIR/dss/deploy-ilk" "BUSDDAI" "${1:-"A"}" "GemJoinLP"
