#!/usr/bin/env bash

#  Copyright (C) 2020 Freeliquid

#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

# shellcheck source=lib/common.sh
. "$LIB_DIR/common.sh"


test -z "$MCD_GOV" && echo "There is no MCD_GOV configured" && exit 1

FL_UNI_ADAPTER_STABLES=$(dappCreate binance-fl-ct-optimized UniswapAdapterForStables)
log "FL_UNI_ADAPTER_STABLES=$FL_UNI_ADAPTER_STABLES"
export FL_UNI_ADAPTER_STABLES
